### ISSUE TITLE
Implement input and output function

### ISSUE THREAD

**Issue by TerenceNg03** [tohanss/DECIDE#54]
The program should be able to read from the console and output a string.

**Comment by tohanss** [comment]
Input function could probably be a placeholder right now since input is undefined

**Comment by tohanss** [comment]
Place test input in a JSON file and create an input function that creates:

* an object from the Parameters class
* numPoints
* LCM
* PUV

The Decide() function should then have all this data. The black box of Decide() will be implemented by another issue.
